name: Create pull request for scala-steward-dependencies branches
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * MON"

jobs:
  create-develop-pr:
    runs-on: ubuntu-latest
    name: Create PR from `scala-steward-dependencies` to `main/master` for multiple repositories
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Read repositories from file
        id: read-repos
        run: |
            repos_content=""
            while IFS= read -r line; do
            repo_name=$(echo "$line" | sed -e 's/^- //' -e 's/:scala-steward-dependencies//')
            repos_content+="$repo_name "
            done < repos.md
            echo -e "::set-output name=repos::$repos_content"
        shell: bash

      - name: Create Pull Request
        run: |
          for repo in ${{ steps.read-repos.outputs.repos }}; do
            default_branch=$(gh api /repos/$repo -q '.default_branch')
            scala_steward_branch=$(gh api /repos/$repo/commits/refs/heads/scala-steward-dependencies -q '.sha')
            main=$(gh api /repos/$repo/commits/refs/heads/$default_branch -q '.sha')

            if [[ $scala_steward_branch != $main ]]; then
                gh api /repos/$repo/pulls \
                  -f title="Scala Steward Updates" \
                  -f base=$default_branch \
                  -f head=scala-steward-dependencies
            else
                echo "There are no updates in $repo"
            fi
          done
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_PAT }}
