name: TDR Deploy to ECS
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      service:
        required: true
        type: string
      image-name:
        required: true
        type: string
      to-deploy:
        required: true
        type: string
    secrets:
      ACCOUNT_NUMBER:
        required: true
      MANAGEMENT_ACCOUNT:
        required: true
      WORKFLOW_PAT:
        required: true
      SLACK_WEBHOOK:
        required: true

permissions: {}
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: refs/tags/${{ inputs.to-deploy }}
          persist-credentials: false
      - name: Configure AWS credentials for ECR
        uses: aws-actions/configure-aws-credentials@ec61189d14ec14c8efccab744f656cffd0e33f37 # v6.1.0
        with:
          role-to-assume: arn:aws:iam::${{ secrets.MANAGEMENT_ACCOUNT }}:role/TDRGithubActionsRoleMgmt
          aws-region: eu-west-2
          role-session-name: ECRLogin
      - id: role-name
        run: |
          import os
          with open(os.environ['GITHUB_OUTPUT'], 'a') as fh: 
            print(f"role-name=TDRGitHubECSUpdateRole{os.environ['DEPLOY_ENVIRONMENT'].title()}", file=fh)
        shell: python
        env:
          DEPLOY_ENVIRONMENT: ${{ inputs.environment }}
      - name: Login to ECR
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
        with:
          registry: ${{ secrets.MANAGEMENT_ACCOUNT }}.dkr.ecr.eu-west-2.amazonaws.com
      - name: Tag image
        run: |
          docker pull "${MANAGEMENT_ACCOUNT}.dkr.ecr.eu-west-2.amazonaws.com/${IMAGE_NAME}:${TO_DEPLOY}"
          docker tag "${MANAGEMENT_ACCOUNT}.dkr.ecr.eu-west-2.amazonaws.com/${IMAGE_NAME}:${TO_DEPLOY}" "${MANAGEMENT_ACCOUNT}.dkr.ecr.eu-west-2.amazonaws.com/${IMAGE_NAME}:${DEPLOY_ENVIRONMENT}"
          docker push "${MANAGEMENT_ACCOUNT}.dkr.ecr.eu-west-2.amazonaws.com/${IMAGE_NAME}:${DEPLOY_ENVIRONMENT}"
        env:
          MANAGEMENT_ACCOUNT: ${{ secrets.MANAGEMENT_ACCOUNT }}
          IMAGE_NAME: ${{ inputs.image-name }}
          TO_DEPLOY: ${{ inputs.to-deploy }}
          DEPLOY_ENVIRONMENT: ${{ inputs.environment }}
      - name: Configure AWS credentials for ECS
        uses: aws-actions/configure-aws-credentials@ec61189d14ec14c8efccab744f656cffd0e33f37 # v6.1.0
        with:
          role-to-assume: arn:aws:iam::${{ secrets.ACCOUNT_NUMBER }}:role/${{ steps.role-name.outputs.role-name }}
          aws-region: eu-west-2
          role-session-name: ECRLogin
      - name: Deploy to ECS
        run: aws ecs update-service --service "${SERVICE}_service_${DEPLOY_ENVIRONMENT}" --cluster "${SERVICE}_${DEPLOY_ENVIRONMENT}" --force-new-deployment > /dev/null
        env:
          SERVICE: ${{ inputs.service }}
          DEPLOY_ENVIRONMENT: ${{ inputs.environment }}
      - name: Get current and prior release commits
        id: release-commits
        run: |
          CURRENT_COMMIT=$(git rev-parse HEAD)
          PRIOR_RELEASE_COMMIT=$(git ls-remote origin "release-${DEPLOY_ENVIRONMENT}" | cut -f1 2>/dev/null || echo "")
          echo "current-commit=$CURRENT_COMMIT" >> $GITHUB_OUTPUT
          echo "prior-release-commit=$PRIOR_RELEASE_COMMIT" >> $GITHUB_OUTPUT
        env:
          DEPLOY_ENVIRONMENT: ${{ inputs.environment }}
      - name: Send success message
        uses: nationalarchives/tdr-github-actions/.github/actions/slack-send@8f8b90556173b43554c22d6b5f192fe9f26ad8ab # v0.0.36
        with:
          message: ":white_check_mark: Service ${{ inputs.image-name }} updated to version ${{ inputs.to-deploy }} in ${{ inputs.environment }} (<https://github.com/${{ github.repository }}/compare/${{ steps.release-commits.outputs.prior-release-commit }}...${{ steps.release-commits.outputs.current-commit }}|See changes>)"
          slack-url: ${{ secrets.SLACK_WEBHOOK }}
      - name: Update release branch
        run: |
          git remote set-url origin "https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
          git branch -f "release-${DEPLOY_ENVIRONMENT}" HEAD
          git push -f origin "release-${DEPLOY_ENVIRONMENT}"
        env:
          GITHUB_TOKEN: ${{ github.token }}
          DEPLOY_ENVIRONMENT: ${{ inputs.environment }}
      - name: Send failure message
        uses: nationalarchives/tdr-github-actions/.github/actions/slack-send@8f8b90556173b43554c22d6b5f192fe9f26ad8ab # v0.0.36
        if: failure()
        with:
          message: ":warning: Build failed for ${{ inputs.image-name }}"
          slack-url: ${{ secrets.SLACK_WEBHOOK }}
      - name: Run E2E tests
        if: inputs.environment != 'prod'
        uses: octokit/request-action@b91aabaa861c777dcdb14e2387e30eddf04619ae # v3.0.0
        with:
          route: POST /repos/nationalarchives/tdr-e2e-tests/actions/workflows/ci.yml/dispatches
          ref: master
          inputs: "{\"environment\": \"${{ inputs.environment }}\", \"wait\": \"300\", \"repo-details\": \"${{ inputs.image-name }}@${{ inputs.to-deploy }}\"}"
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_PAT }}
