name: TDR Deploy to Lambda
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      lambda-name:
        required: true
        type: string
      deployment-package:
        required: true
        type: string
      to-deploy:
        required: true
        type: string
      project:
        type: string
        required: false
        default: 'tdr'
      image-name:
        type: string
        required: false
    secrets:
      ACCOUNT_NUMBER:
        required: true
      MANAGEMENT_ACCOUNT:
        required: true
      WORKFLOW_PAT:
        required: true
      SLACK_WEBHOOK:
        required: true
permissions: {}
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: refs/tags/${{ inputs.to-deploy }}
          persist-credentials: false
      - id: role-name
        run: |
          import os
          with open(os.environ['GITHUB_OUTPUT'], 'a') as fh: 
            print(f"role-name=TDRGithubActionsDeployLambda{os.environ['DEPLOY_ENVIRONMENT'].title()}", file=fh)
        shell: python
        env:
          DEPLOY_ENVIRONMENT: ${{ inputs.environment }}
      - name: Configure AWS credentials for Lambda
        uses: aws-actions/configure-aws-credentials@ec61189d14ec14c8efccab744f656cffd0e33f37 # v6.1.0
        with:
          role-to-assume: arn:aws:iam::${{ secrets.ACCOUNT_NUMBER }}:role/${{ steps.role-name.outputs.role-name }}
          aws-region: eu-west-2
          role-session-name: ECRLogin
      - run: pip install boto3
      - name: Check deployed environment variables
        shell: python
        run: |
          from sys import exit
          from re import findall
          from os.path import exists
          from os import environ
          import boto3
          conf = "src/main/resources/application.conf"
          if exists(conf):
            with open(conf) as file:
              function_name = f"{environ['PROJECT']}-{environ['LAMBDA_NAME']}-{environ['DEPLOY_ENVIRONMENT']}"
              resp = boto3.client("lambda").get_function_configuration(FunctionName=function_name)
              lambda_env_vars = resp.get("Environment", {}).get("Variables", {})
              all_env_vars = filter(lambda x: x != "AWS_LAMBDA_FUNCTION_NAME", findall("\\$\\{([A-Z_]*)\\}", file.read()))
              exit(len(set(all_env_vars).difference(set(lambda_env_vars))))
          else:
            exit(0)
        env:
          PROJECT: ${{ inputs.project }}
          LAMBDA_NAME: ${{ inputs.lambda-name }}
          DEPLOY_ENVIRONMENT: ${{ inputs.environment }}
      - name: Deploy to lambda

        run: |
          if [ -n "${IMAGE_NAME}" ]; then
            aws lambda update-function-code --function-name "${PROJECT}-${LAMBDA_NAME}-${DEPLOY_ENVIRONMENT}" --image-uri "${MANAGEMENT_ACCOUNT}.dkr.ecr.eu-west-2.amazonaws.com/${IMAGE_NAME}:${DEPLOY_ENVIRONMENT}" --output text --query 'FunctionName'
          else
            aws lambda update-function-code --function-name "${PROJECT}-${LAMBDA_NAME}-${DEPLOY_ENVIRONMENT}" --s3-bucket tdr-backend-code-mgmt --s3-key "${LAMBDA_NAME}/${TO_DEPLOY}/${DEPLOYMENT_PACKAGE}" --output text --query 'FunctionName'
          fi
          aws lambda wait function-updated --function-name "${PROJECT}-${LAMBDA_NAME}-${DEPLOY_ENVIRONMENT}"
        env:
          IMAGE_NAME: ${{ inputs.image-name }}
          PROJECT: ${{ inputs.project }}
          LAMBDA_NAME: ${{ inputs.lambda-name }}
          DEPLOY_ENVIRONMENT: ${{ inputs.environment }}
          MANAGEMENT_ACCOUNT: ${{ secrets.MANAGEMENT_ACCOUNT }}
          TO_DEPLOY: ${{ inputs.to-deploy }}
          DEPLOYMENT_PACKAGE: ${{ inputs.deployment-package }}
      - name: Get current and prior release commits
        id: release-commits
        run: |
          CURRENT_COMMIT=$(git rev-parse HEAD)
          PRIOR_RELEASE_COMMIT=$(git ls-remote origin "release-${DEPLOY_ENVIRONMENT}" | cut -f1 2>/dev/null || echo "")
          echo "current-commit=$CURRENT_COMMIT" >> $GITHUB_OUTPUT
          echo "prior-release-commit=$PRIOR_RELEASE_COMMIT" >> $GITHUB_OUTPUT
        env:
          DEPLOY_ENVIRONMENT: ${{ inputs.environment }}
      - name: Send success message
        uses: nationalarchives/tdr-github-actions/.github/actions/slack-send@9214d929d74b527c75cdac14ba96812f90b3ebba # v0.0.35
        with:
          message: ":white_check_mark: Lambda ${{ inputs.lambda-name }} updated to version ${{ inputs.to-deploy }} in ${{ inputs.environment }} (<https://github.com/${{ github.repository }}/compare/${{ steps.release-commits.outputs.prior-release-commit }}...${{ steps.release-commits.outputs.current-commit }}|See changes>)"
          slack-url: ${{ secrets.SLACK_WEBHOOK }}
      - name: Update release branch
        run: |
          git remote set-url origin "https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
          git branch -f "release-${DEPLOY_ENVIRONMENT}" HEAD
          git push -f origin "release-${DEPLOY_ENVIRONMENT}"
        env:
          GITHUB_TOKEN: ${{ github.token }}
          DEPLOY_ENVIRONMENT: ${{ inputs.environment }}
      - name: Send failure message
        uses: nationalarchives/tdr-github-actions/.github/actions/slack-send@9214d929d74b527c75cdac14ba96812f90b3ebba # v0.0.35
        if: failure()
        with:
          message: ":warning: Build failed for ${{ inputs.lambda-name }}"
          slack-url: ${{ secrets.SLACK_WEBHOOK }}
      - name: Run E2E tests
        if: inputs.environment != 'prod' && inputs.environment != 'mgmt'
        uses: octokit/request-action@b91aabaa861c777dcdb14e2387e30eddf04619ae # v3.0.0
        with:
          route: POST /repos/nationalarchives/tdr-e2e-tests/actions/workflows/ci.yml/dispatches
          ref: master
          inputs: "{\"environment\": \"${{ inputs.environment }}\", \"repo-details\": \"${{ inputs.lambda-name }}@${{ inputs.to-deploy }}\"}"
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_PAT }}
