name: TDR SBT Release
on:
  workflow_call:
    inputs:
      library-name:
        required: false
        type: string
        description: The name of the library to publish
    secrets:
      WORKFLOW_PAT:
        required: true
      SLACK_WEBHOOK:
        required: true
      SONATYPE_USERNAME:
        required: true
      SONATYPE_PASSWORD:
        required: true
      GPG_PRIVATE_KEY:
        required: true
      GPG_PASSPHRASE:
        required: true
env:
  RUN_NUMBER: ${{ github.run_id }}${{ github.run_attempt }}
  BRANCH_NAME: version-bump-${{ github.run_id }}${{ github.run_attempt }}
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: sbt/setup-sbt@508b753e53cb6095967669e0911487d2b9bc9f41 # v1.1.22
      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@2dc316deee8e90f13e1a351ab510b4d5bc0c82cd # v7.0.0
        with:
          git_user_signingkey: true
          git_commit_gpgsign: true
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
      - run: |
          git config --global user.email 181243999+tna-da-bot@users.noreply.github.com
          git config --global user.name tna-da-bot
          git remote set-url origin https://x-access-token:${WORKFLOW_PAT}@github.com/${{ github.repository }}.git
          git checkout -b "$BRANCH_NAME"
          git push -u origin "$BRANCH_NAME"
          sbt 'release with-defaults'
        env:
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          WORKFLOW_PAT: ${{ secrets.WORKFLOW_PAT }}
      - name: Create Pull Request
        run: gh pr create --fill --label 'Version bump'
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_PAT }}
      - name: Send success message
        uses: nationalarchives/tdr-github-actions/.github/actions/slack-send@683912c0ebb8d5d6edd15a222677395e95d12ce0 # v0.0.24
        with:
          message: ":white_check_mark: ${{ env.LIBRARY_NAME }} has been published"
          slack-url: ${{ secrets.SLACK_WEBHOOK }}
        env:
          LIBRARY_NAME: ${{ inputs.library-name }}
