name: TDR Run git secrets and tests
on:
  workflow_call:
    inputs:
      use-workspace:
        type: boolean
        required: false
        default: true
      working-directory:
        type: string
        required: false
        default: .
      terraform-version:
        type: string
        required: false
        default: 1.9.8
    secrets:
      MANAGEMENT_ACCOUNT:
        required: true
      WORKFLOW_PAT:
        required: true
jobs:
  terraform-check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: recursive
          token: ${{ secrets.WORKFLOW_PAT }}
      - name: Configure AWS credentials for Lambda
        uses: aws-actions/configure-aws-credentials@ec61189d14ec14c8efccab744f656cffd0e33f37 # v6.1.0
        with:
          role-to-assume: arn:aws:iam::${{ secrets.MANAGEMENT_ACCOUNT }}:role/TDRGithubTerraformAssumeRoleIntg
          aws-region: eu-west-2
          role-session-name: TerraformRole
      - uses: nationalarchives/tdr-github-actions/.github/actions/run-git-secrets@b6ba669dcee7fd4ac089c2e9fb234c48ddd93ab5 # v0.0.15
      - uses: nationalarchives/tdr-github-actions/.github/actions/slack-send@b6ba669dcee7fd4ac089c2e9fb234c48ddd93ab5 # v0.0.15
        if: failure()
        with:
          message: ":warning: Secrets found in repository ${{ inputs.repo-name }}"
          slack-url: ${{ secrets.SLACK_WEBHOOK }}
      - uses: hashicorp/setup-terraform@5e8dbf3c6d9deaf4193ca7a8fb23f2ac83bb6c85 # v4.0.0
        with:
          terraform_version: ${{ inputs.terraform-version }}
      - name: Terraform Format
        id: fmt
        run: terraform fmt -check --recursive
      - name: Terraform Init
        id: init
        run: terraform init
      - name: Select integration workspace
        if: inputs.use-workspace
        run: terraform workspace select intg
      - name: Terraform Validate
        id: validate
        run: terraform validate
