name: TDR Terraform plan and apply
on:
  workflow_call:
    inputs:
      working-directory:
        type: string
        required: false
        default: .
      repo-name:
        type: string
        required: true
      environment:
        type: string
        required: true
      terraform-version:
        type: string
        required: false
        default: 1.9.8
      project:
        type: string
        required: false
        default: 'tdr'
      update-tag:
        type: boolean
        required: false
        default: true
    secrets:
      MANAGEMENT_ACCOUNT:
        required: true
      WORKFLOW_PAT:
        required: true
      SLACK_WEBHOOK:
        required: true
      ACCOUNT_NUMBER:
        required: true
      INTG_ACCOUNT_NUMBER:
        required: false
      STAGING_ACCOUNT_NUMBER:
        required: false
      PROD_ACCOUNT_NUMBER:
        required: false
      DEV_ACCOUNT_NUMBER:
        required: false
jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      title-environment: ${{ steps.set-environment-names.outputs.title_environment }}
    steps:
      - id: set-environment-names
        env:
          INPUT_ENVIRONMENT: ${{ inputs.environment }}
        run: |
          import os
          env = os.environ['INPUT_ENVIRONMENT']
          with open(os.environ['GITHUB_OUTPUT'], 'a') as fh:
            print(f"title_environment={env.title()}", file=fh)
        shell: python
  plan:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    needs: setup
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: recursive
          token: ${{ secrets.WORKFLOW_PAT }}
      - name: Configure AWS credentials for Lambda
        uses: aws-actions/configure-aws-credentials@d979d5b3a71173a29b74b5b88418bfda9437d885 # v6.1.1
        with:
          role-to-assume: arn:aws:iam::${{ secrets.MANAGEMENT_ACCOUNT }}:role/TDRGithubTerraformAssumeRole${{ needs.setup.outputs.title-environment }}
          aws-region: eu-west-2
          role-session-name: TerraformRole
      - uses: hashicorp/setup-terraform@5e8dbf3c6d9deaf4193ca7a8fb23f2ac83bb6c85 # v4.0.0
        with:
          terraform_version: ${{ inputs.terraform-version }}
      - name: Terraform Plan
        id: plan
        env:
          GITHUB_OWNER: nationalarchives
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_PAT }}
          TF_ACCOUNT_INTG: ${{ secrets.INTG_ACCOUNT_NUMBER }}
          TF_ACCOUNT_STAGING: ${{ secrets.STAGING_ACCOUNT_NUMBER }}
          TF_ACCOUNT_PROD: ${{ secrets.PROD_ACCOUNT_NUMBER }}
          TF_ACCOUNT_DEV: ${{ secrets.DEV_ACCOUNT_NUMBER }}
          # 'hosting_project' Terraform variable required to support reference generator service Terraform
          TF_VAR_hosting_project: ${{ inputs.project }}
          TF_ENVIRONMENT: ${{ inputs.environment }}
          GH_RUN_ID: ${{ github.run_id }}
          GH_RUN_ATTEMPT: ${{ github.run_attempt }}
        run: |
          case "$TF_ENVIRONMENT" in
            intg)    export TF_VAR_tdr_account_number="$TF_ACCOUNT_INTG" ;;
            staging) export TF_VAR_tdr_account_number="$TF_ACCOUNT_STAGING" ;;
            dev)     export TF_VAR_tdr_account_number="$TF_ACCOUNT_DEV" ;;
            *)       export TF_VAR_tdr_account_number="$TF_ACCOUNT_PROD" ;;
          esac
          terraform init
          terraform workspace select "$TF_ENVIRONMENT"
          pip install boto3
          terraform plan -no-color -out=out > /dev/null
          terraform show -no-color out > out.plan
          python $GITHUB_WORKSPACE/.github/scripts/logs.py out.plan "${GH_RUN_ID}${GH_RUN_ATTEMPT}" "terraform-plan-outputs-${TF_ENVIRONMENT}"
      - uses: nationalarchives/tdr-github-actions/.github/actions/slack-send@e7b57a3bdf7863c951cd203101c6d566986376e3 # v0.0.38
        with:
          message: |
            :book: Terraform plan ready for repository ${{ inputs.repo-name }} environment ${{ inputs.environment }}
            :log: View the <${{ steps.plan.outputs.log-url }}|plan logs> in the management account.
            :white_check_mark: <https://github.com/nationalarchives/${{ inputs.repo-name }}/actions/runs/${{ github.run_id }}|Approve the workflow>
          slack-url: ${{ secrets.SLACK_WEBHOOK }}
  apply:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    needs:
      - plan
      - setup
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: recursive
          token: ${{ secrets.WORKFLOW_PAT }}
      - name: Configure AWS credentials for Lambda
        uses: aws-actions/configure-aws-credentials@d979d5b3a71173a29b74b5b88418bfda9437d885 # v6.1.1
        with:
          role-to-assume: arn:aws:iam::${{ secrets.MANAGEMENT_ACCOUNT }}:role/TDRGithubTerraformAssumeRole${{ needs.setup.outputs.title-environment }}
          aws-region: eu-west-2
          role-session-name: TerraformRole
      - uses: hashicorp/setup-terraform@5e8dbf3c6d9deaf4193ca7a8fb23f2ac83bb6c85 # v4.0.0
        with:
          terraform_version: ${{ inputs.terraform-version }}
      - name: Run apply
        env:
          GITHUB_OWNER: nationalarchives
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_PAT }}
          TF_VAR_tdr_account_number: ${{ secrets.ACCOUNT_NUMBER }}
          # 'hosting_project' Terraform variable required to support reference generator service Terraform
          TF_VAR_hosting_project: ${{ inputs.project }}
          TF_ENVIRONMENT: ${{ inputs.environment }}
        run: |
          terraform init
          terraform workspace select "$TF_ENVIRONMENT"
          terraform apply --auto-approve -no-color > apply_output.txt 2>&1
      - name: Upload logs
        id: apply-logs
        if: failure()
        env:
          GH_RUN_ID: ${{ github.run_id }}
          GH_RUN_ATTEMPT: ${{ github.run_attempt }}
          TF_ENVIRONMENT: ${{ inputs.environment }}
        run: |
          pip install boto3
          python $GITHUB_WORKSPACE/.github/scripts/logs.py apply_output.txt "${GH_RUN_ID}${GH_RUN_ATTEMPT}" "terraform-apply-outputs-${TF_ENVIRONMENT}"
      - id: next-tag
        uses: nationalarchives/tdr-github-actions/.github/actions/get-next-version@e7b57a3bdf7863c951cd203101c6d566986376e3 # v0.0.38
        with:
          repo-name: ${{ inputs.repo-name }}
      - name: Run git tag
        if: ${{ inputs.update-tag }}
        env:
          NEXT_VERSION: ${{ steps.next-tag.outputs.next-version }}
          DEPLOY_ENVIRONMENT: ${{ inputs.environment }}
        run: |
          git tag "$NEXT_VERSION"
          git push origin "$NEXT_VERSION"
          git branch -f "release-${DEPLOY_ENVIRONMENT}" HEAD
          git push -f origin "release-${DEPLOY_ENVIRONMENT}"
      - name: Send failure message
        if: failure()
        uses: nationalarchives/tdr-github-actions/.github/actions/slack-send@e7b57a3bdf7863c951cd203101c6d566986376e3 # v0.0.38
        with:
          message: |
            :warning: ${{ inputs.repo-name }} deploy failed for ${{ inputs.environment }}
            :log: View the <${{ steps.apply-logs.outputs.log-url }}|apply logs> in the management account.
          slack-url: ${{ secrets.SLACK_WEBHOOK }}
      - name: Send success message
        uses: nationalarchives/tdr-github-actions/.github/actions/slack-send@e7b57a3bdf7863c951cd203101c6d566986376e3 # v0.0.38
        with:
          message: ":white_check_mark: ${{ inputs.repo-name }} deploy successful for ${{ inputs.environment }}"
          slack-url: ${{ secrets.SLACK_WEBHOOK }}
      - name: Run E2E tests
        if: inputs.environment != 'prod'
        uses: octokit/request-action@b91aabaa861c777dcdb14e2387e30eddf04619ae # v3.0.0
        with:
          route: POST /repos/nationalarchives/tdr-e2e-tests/actions/workflows/ci.yml/dispatches
          ref: master
          inputs: "{\"environment\": \"${{ inputs.environment }}\", \"repo-details\": \"${{ inputs.repo-name }}\"}"
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_PAT }}
